language: ruby
rvm:
  - 2.1.0
  - rbx-2
  - ruby-head
  - jruby-head
before_install:
  # bundler installation needed for jruby-head
  # https://github.com/travis-ci/travis-ci/issues/5861
  - gem install bundler
